[package]
name = "dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.3"
minifb = "0.25.0"
cargo-bundle = "0.6.0"